name: HashiCorp Sentinel
on: [push]
jobs:
  test-policies:
    runs-on: ubuntu-latest
    container:
      image: thrashr888/sentinel-simulator
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Sentinel policies
        run: sentinel test $(find . -name "*.sentinel" ! -path "*/testdata/*")